from pathlib import Path
import pandas as pd
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
RAW=ROOT/'data'/'raw'; REF=ROOT/'data'/'reference'; PROCESSED=ROOT/'data'/'processed'; REPORTS=ROOT/'outputs'/'reports'; FIGURES=ROOT/'outputs'/'figures'; PBI=ROOT/'outputs'/'powerbi'
ANALYSIS_DATE=pd.Timestamp('2026-06-02')
for p in [PROCESSED,REPORTS,FIGURES,PBI]: p.mkdir(parents=True,exist_ok=True)

asset=pd.read_csv(PROCESSED/'asset_lifecycle_analysis.csv'); sw=pd.read_csv(PROCESSED/'software_lifecycle_analysis.csv'); bu=pd.read_csv(REF/'business_units.csv')
a=asset.merge(bu,on='Business_Unit_ID',how='left')
bu_sum=a.groupby(['Business_Unit_ID','Business_Unit_Name']).agg(Total_Assets=('Asset_ID','count'),Past_EOL_Assets=('Past_EOL_Flag','sum'),Expiring_12M_Assets=('Expiring_12M_Flag','sum'),Critical_Vulnerability_Count=('Critical_Vulnerability_Count','sum'),Total_Replacement_Cost=('Replacement_Cost','sum'),Total_Downtime_Hours=('Downtime_Hours','sum'),Avg_Risk_Score=('Lifecycle_Risk_Score','mean')).reset_index(); bu_sum['Past_EOL_Pct']=(bu_sum.Past_EOL_Assets/bu_sum.Total_Assets*100).round(2); bu_sum['Risk_Band']=pd.cut(bu_sum.Avg_Risk_Score,[-1,25,45,65,100],labels=['Low','Medium','High','Critical'])
bu_sum.to_csv(REPORTS/'business_unit_eol_exposure.csv',index=False); bu_sum.to_csv(REPORTS/'risk_heatmap_business_unit.csv',index=False)
cyber=asset[(asset.Lifecycle_Status=='Past EOL')&((asset.Critical_Vulnerability_Count>0)|(asset.High_Vulnerability_Count>1))].copy(); cyber['Remediation_Priority']='Immediate'; cyber['Cyber_Risk_Category']=np.where(cyber.Asset_Type.isin(['Server','Firewall','Router','Core Switch','Distribution Switch','Storage']),'Infrastructure','End User Computing / Branch'); cyber.to_csv(REPORTS/'past_eol_critical_vulnerability_assets.csv',index=False)
cyber.groupby('Asset_Type').agg(Asset_Count=('Asset_ID','count'),Critical_Vulnerabilities=('Critical_Vulnerability_Count','sum')).reset_index().to_csv(REPORTS/'cybersecurity_unsupported_critical_summary.csv',index=False)
sw_sum=sw.groupby(['Software_Name','Software_Version','Publisher','Software_Category','Software_EOL_Status','Software_Compliance_Risk']).agg(Installation_Count=('Installation_ID','count'),Asset_Count=('Asset_ID','nunique')).reset_index().sort_values('Installation_Count',ascending=False); sw_sum.to_csv(REPORTS/'software_compliance_risk_summary.csv',index=False); sw_sum.to_csv(REPORTS/'compliance_software_versions_summary.csv',index=False)
asset.groupby(['Asset_Type','Lifecycle_Status']).agg(Asset_Count=('Asset_ID','count'),Replacement_Cost=('Replacement_Cost','sum')).reset_index().to_csv(REPORTS/'lifecycle_exposure_by_asset_type.csv',index=False)
refresh=asset[asset.Lifecycle_Status.isin(['Past EOL','Expiring in 12 Months','Expiring in 24 Months'])].copy(); refresh['Refresh_Year']=np.select([refresh.Lifecycle_Status=='Past EOL',refresh.Lifecycle_Status=='Expiring in 12 Months'],[2026,2027],default=2028); refresh.groupby('Refresh_Year').agg(Assets=('Asset_ID','count'),Estimated_Refresh_Cost=('Replacement_Cost','sum')).reset_index().to_csv(REPORTS/'refresh_budget_planning_summary.csv',index=False)
op=asset.groupby('Lifecycle_Status').agg(Asset_Count=('Asset_ID','count'),Incident_Count=('Incident_Count','sum'),Downtime_Hours=('Downtime_Hours','sum'),Avg_Downtime_Per_Asset=('Downtime_Hours','mean'),Avg_Incidents_Per_Asset=('Incident_Count','mean')).reset_index(); op.to_csv(REPORTS/'operational_impact_by_lifecycle_status.csv',index=False); op.to_csv(REPORTS/'incident_downtime_by_lifecycle.csv',index=False)
pd.DataFrame([['Total managed assets',len(asset)],['Assets already past vendor support',int((asset.Lifecycle_Status=='Past EOL').sum())],['Assets expiring within 12 months',int((asset.Lifecycle_Status=='Expiring in 12 Months').sum())],['Past-EOL assets with critical/high vulnerabilities',len(cyber)],['Estimated refresh cost for past/near EOL assets',round(float(refresh.Replacement_Cost.sum()),2)],['Downtime hours linked to past-EOL assets',round(float(asset.loc[asset.Lifecycle_Status=='Past EOL','Downtime_Hours'].sum()),2)]],columns=['Executive_Question','Executive_Answer']).to_csv(REPORTS/'executive_questions_summary.csv',index=False)
pd.DataFrame([['Immediate','Remediate unsupported assets with critical vulnerabilities','Cybersecurity','0-6 Months','Focus on infrastructure and branch technologies with open critical findings.'],['Immediate','Prioritize highest-risk business units','Technology Governance','0-12 Months','Use risk heatmap to sequence high-exposure functions.'],['Near Term','Fund lifecycle refresh program','Infrastructure','FY2026-FY2028','Align refresh budget to forecasted replacement requirements.'],['Near Term','Reduce unsupported software footprint','Enterprise Architecture','0-12 Months','Target unsupported productivity, database, runtime, and development tooling versions.'],['Strategic','Implement lifecycle governance controls','Technology Risk','Ongoing','Maintain annual EOL forecasts and exception governance.']],columns=['Priority','Recommended_Action','Owner','Timeframe','Rationale']).to_csv(REPORTS/'recommendation_actions.csv',index=False)
print('Analytics reports exported')
